import { join } from "node:path"

import { ensureCleanDirectory, ensureDirectory, readJsonFileOrNull, readTextFileOrNull, removeManagedSection, toPosixPath, upsertManagedSection, writeJsonFile, writeTextFile } from "./files.js"
import type { ActivationManifest, WirePlanManifest, WirePreviewManifest } from "./types.js"

export async function wireOpenCode(options: {
  projectRoot: string
  workspaceRoot: string
  mode: "preview" | "apply" | "reset"
}): Promise<void> {
  const { projectRoot, workspaceRoot, mode } = options
  const activationRoot = join(projectRoot, "activate", "opencode")
  const activationManifest = await readJsonFileOrNull<ActivationManifest>(join(activationRoot, "activation-manifest.json"))

  const localOverlayRoot = join(workspaceRoot, ".opencode")
  const localContextRoot = join(localOverlayRoot, "context", "project-intelligence", "agent-harness")
  const localAgentsPath = join(workspaceRoot, "AGENTS.md")

  const preview: WirePreviewManifest = {
    schemaVersion: 1,
    host: "opencode",
    mode,
    generatedAt: new Date().toISOString(),
    workspaceRoot: toPosixPath(workspaceRoot),
    targetPaths: [
      toPosixPath(localContextRoot),
      toPosixPath(localAgentsPath)
    ],
    notes: [
      "OpenCode wire-in writes a project-local overlay under .opencode/context/project-intelligence/agent-harness.",
      "The global OpenAgentsControl-managed install is not modified."
    ]
  }

  await writeJsonFile(join(activationRoot, "wire-preview-opencode.json"), preview)

  if (mode === "preview") {
    return
  }

  if (mode === "reset") {
    const existingAgentsContent = (await readTextFileOrNull(localAgentsPath)) ?? ""
    const nextAgentsContent = removeManagedSection({
      originalContent: existingAgentsContent,
      markerId: "agent-harness"
    })
    await writeTextFile(localAgentsPath, nextAgentsContent)
    await writeTextFile(join(localContextRoot, "activation-manifest.json"), "")
    return
  }

  await ensureCleanDirectory(localContextRoot)

  await writeJsonFile(join(localContextRoot, "activation-manifest.json"), activationManifest ?? {
    schemaVersion: 1,
    host: "opencode",
    generatedAt: new Date().toISOString(),
    activeBundles: [],
    activeAssets: [],
    runtimeRoot: toPosixPath(localContextRoot),
    notes: ["No OpenCode activation manifest was found at apply time."]
  })

  const agentsContent = buildManagedAgentsSection(activationManifest)
  const existingAgentsContent = (await readTextFileOrNull(localAgentsPath)) ?? ""
  const nextAgentsContent = upsertManagedSection({
    originalContent: existingAgentsContent,
    markerId: "agent-harness",
    bodyLines: agentsContent.split("\n")
  })
  await writeTextFile(localAgentsPath, nextAgentsContent)

  const wirePlan: WirePlanManifest = {
    schemaVersion: 1,
    host: "opencode-project",
    generatedAt: new Date().toISOString(),
    workspaceRoot: toPosixPath(workspaceRoot),
    runtimeRoot: toPosixPath(localOverlayRoot),
    notes: [
      "Project-local OpenCode overlay written under .opencode/context/project-intelligence/agent-harness.",
      "AGENTS.md managed section updated to expose curated activation context without overriding global OpenAgentsControl state."
    ]
  }

  await writeJsonFile(join(localContextRoot, "wire-plan.json"), wirePlan)
}

function buildManagedAgentsSection(activationManifest: ActivationManifest | null): string {
  const assetLines = (activationManifest?.activeAssets ?? []).map((assetId) => `- ${assetId}`)

  return [
    "## agent-harness managed overlay",
    "",
    "This workspace is wired to a curated OpenCode overlay generated by agent-harness.",
    "",
    "### Active assets",
    ...assetLines,
    ""
  ].join("\n")
}
